### ISSUE TITLE
Cannot install your environment

### ISSUE THREAD

**Issue by zwbgood6** [thanard/causal-infogan#1]
I find there may something wrong with the tf14.yml code.

I cannot install your environment because of there lines:
```
- gym (/home/thanard/anaconda3/envs/tf14/lib/python3.5/site-packages)==0.8.0
- lasagne==0.2.dev1
- theano==0.9.0.dev1
- torch==0.4.0a0+67494ce
```

I believe we shall change the code to:
```
- gym)==0.8.0
- lasagne==0.1
- theano==0.9.0
- torch==0.4.0
```

Is it correct?

**Comment by thanard** [comment]
Thanks a lot. I have just fixed it.
